[package]
name = "gps"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
chrono = "0.4.34"
dashmap = "5.5.3"
once_cell = "1.19.0"
tokio = { version = "1.36.0", features = ["full"] }
axum = { version = "0.6.20", features = ["ws","multipart","macros"] }
